spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.250.207:13306/letsbim-library?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull
    username: remote-client
    password: ZAQ!2wsx
    # hikari 链接池配置
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认60000 也就是10分钟
      idle-timeout: 300000
      # 最大连接池，默认10
      maximum-pool-size: 12
      # 从连接池返回的连接默认自动提交行为，默认true
      auto-commit: true
      # 连接池名称
      pool-name: riskHikariCp
      # 连接池中连接最长生命周期，如果为0表示无限生命周期，默认1800000即为30分钟
      max-lifetime: 1200000
      # 数据库连接超时时间，默认30s 即30000
      connection-timeout: 20000
      connection-test-query: select now()
  redis:
    enable: true
    host: 192.168.250.145
    port: 6379
    password: lets@redis!
    timeout: 3000
    database: 0
    ssl: false
    minIdle: 5
    maxIdle: 10
    maxTotal: 50
    maxWaitMillis: 10000
    testOnBorrow: true
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 1800000
    softMinEvictableIdleTimeMillis: 10000
    testWhileIdle: true
    blockWhenExhausted: false

# token配置
token:
  secret: fewjaiofjaewoifjgneaoiew